- hosts: localhost
  connection: local
  become: true
  vars:
  - dockerfile_folder: "dockerfiles"
  - docker_image_name: "kather"
  - docker_container_name: "kather"
  - patting_ssh_port: "12222"
  - patting_http_port: "18080"
  tasks:
  - name: "Check if pubkey exists"
    stat:
      path: "{{dockerfile_folder}}/katherkey.pub"
    register: katherkey_exists

  - name: "Generate katherkey for ssh"
    command: "ssh-keygen -f {{dockerfile_folder}}/katherkey -q -N ''"
    when: katherkey_exists.stat.exists == False

  - name: "change mode of katherkey.pub"
    file:
      path: "{{dockerfile_folder}}/katherkey.pub"
      mode: u+rw,g+r,o+r
    when: katherkey_exists.stat.exists == True

  - name: "change mode of katherkey"
    file:
      path: "{{dockerfile_folder}}/katherkey"
      mode: u+rw,g+r,o+r

  - name: "Copy Docker file"
    copy:
     src: "{{dockerfile_folder}}"
     dest: "/srv/"

  - name: "Build docker image from Dockerfile"
    docker_image:
       name:  "{{docker_image_name}}"
       build:
         pull: yes
         path: "/srv/{{dockerfile_folder}}/"
       state: present
       source: build

  - name: "launch docker container"
    docker_container:
       name: "{{docker_container_name}}"
       image: "{{docker_image_name}}"
       state: started
       restart: yes
       recreate: yes
       ports:
       - "{{patting_ssh_port}}:22"
       # -  "{{patting_http_port}}:8080"
    register: docker_info

  - name: "Update inventory file"
    lineinfile:
      path: "/etc/ansible/hosts"
      insertafter: '^\[containers]'
      firstmatch: yes
      line: "{{docker_info.ansible_facts.docker_container.NetworkSettings.IPAddress}}"
      state: present
